### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by 2x-Helix** [azlibdar/vscode-explorer-ui#1]
Hey @azlibdar,

Great implementation of a file explorer with the file and folder management, couldn't really find anything like this out of the box. I would like to use it as part of some work, would you consider releasing this under an open source license?

**Comment by azlanibrahim1** [comment]
Thank you for your kind words! I'm glad you found the file explorer
implementation useful. I've created a license for the project, and you're
welcome to use and modify it as needed for your work.

It would be amazing to see how you're using it once your project is ready!
Feel free to share any updates or feedback—I’d love to know how it’s
contributing to your work.

Cheers,
Azlan
